#include "ros/ros.h"

// In devel/include/client_service_cpp generated by catkin_make
#include "client_service_cpp/AddTwoInts.h"

// package_name::Service_name(srv file name AddTwoInts.srv)
bool add(client_service_cpp::AddTwoInts::Request  &req,
         client_service_cpp::AddTwoInts::Response &res)
{
  res.sum = req.a + req.b;
  ROS_INFO("request: x=%ld, y=%ld", (long int)req.a, (long int)req.b);
  // > [ INFO] [1646662374.896417434]: request: x=100, y=200

  ROS_INFO("sending back response: [%ld]", (long int)res.sum);
  // > [ INFO] [1646662374.896417434]: request: x=100, y=200
  return true;
}

int main(int argc, char **argv)
{
  // Init server node name "add_two_ints_server"
  ros::init(argc, argv, "add_two_ints_server");
  ros::NodeHandle n;
  
  // Create a service for the "add_two_ints" service,  callback function add
  ros::ServiceServer service = n.advertiseService("add_two_ints", add);
  ROS_INFO("Ready to add two ints.");

  ros::spin();

  return 0;
}
