#include "ros/ros.h"

// In devel/include/client_service_cpp generated by catkin_make
#include "client_service_cpp/AddTwoInts.h"

#include <cstdlib>

int main(int argc, char **argv)
{
  // Init client node name "add_two_ints_client"
  ros::init(argc, argv, "add_two_ints_client");

  // Validate input from command line file_name a b
  if (argc != 3)
  {
    ROS_INFO("usage: add_two_ints_client X Y");
    return 1;
  }

  ros::NodeHandle n;
  
  // Create a client for the "add_two_ints" service.
  ros::ServiceClient client = n.serviceClient<client_service_cpp::AddTwoInts>("add_two_ints");
  client_service_cpp::AddTwoInts srv;
  
  // Write parameter
  srv.request.a = atoll(argv[1]); // srv.request.a = a value
  srv.request.b = atoll(argv[2]); // srv.request.b = b value

  // Call the service with srv parameter
  if (client.call(srv))
  {
    ROS_INFO("Sum: %ld", (long int)srv.response.sum);
  }
  else
  {
    ROS_ERROR("Failed to call service add_two_ints");
    return 1;
  }

  return 0;
}
