#!/usr/bin/env python

# client_service_py was generated by catkin_make
# devel/include/client_service_py 
from client_service_py.srv import AddTwoInts
from client_service_py.srv import AddTwoIntsRequest
from client_service_py.srv import AddTwoIntsResponse

import rospy

# Callback function, run any time when receive message
def handle_add_two_ints(req):
    # Why a, b? => inited in AddTwoInts.srv
    print( "Returnning [%s + %s = %s]"%(req.a, req.b, (req.a + req.b)) )
    # Return response
    return AddTwoIntsResponse(req.a + req.b)

# Create service
def add_two_ints_server():
    # Init node
    rospy.init_node('add_two_ints_server')

    # Init service #### parameter: Service Name, Service Type(.srv file name), Callback function
    s = rospy.Service('add_two_ints', AddTwoInts, handle_add_two_ints)

    print("Ready to add two ints.")
    # Waiting for incoming
    rospy.spin()

if __name__ == "__main__":
    add_two_ints_server()
