#!/usr/bin/env python

import sys
import rospy

# client_service_py was generated by catkin_make
# devel/include/client_service_py
from client_service_py.srv import AddTwoInts
from client_service_py.srv import AddTwoIntsRequest
from client_service_py.srv import AddTwoIntsResponse


def add_two_ints_client(x, y):

    # Make sure the server is awake
    # Parameter: Service Name
    rospy.wait_for_service('add_two_ints')

    try:
        # Create service client, connect to service
        # Parameter: Service Name, Service Type
        add_two_ints = rospy.ServiceProxy('add_two_ints', AddTwoInts)
        # Send value to service x, y > a, b and get response
        respl = add_two_ints(x, y)

        # Why sum => inited in AddTwoInts.srv
        return respl.sum

    except rospy.ServiceException(e):
        print("Service call failed: %s" %e )
    
if __name__ == "__main__":

    # # rosrun client_service_py add_client.py 1 2
    # print(len(sys.argv)) # 3
    # print(sys.argv[0]) # File path
    # print(sys.argv[1]) # 1
    # print(sys.argv[2]) # 2

    # Use sys.argv when using the command line
    if len(sys.argv) == 3:
        x = int(sys.argv[1])
        y = int(sys.argv[2])
    else:
        print("%s [x y]"%sys.argv[0])
        sys.exit(1)

    print("Requesting %s + %s"%(x,y))
    # Request to server
    s = add_two_ints_client(x, y)

    print("%s + %s = %s"%(x, y, s))
